//! `SeaORM` Entity. Generated by sea-orm-codegen 0.11.3

pub use super::game_tags::Entity as GameTags;
pub use super::games::Entity as Games;
pub use super::optimal_session_length::Entity as OptimalSessionLength;
pub use super::player_games::Entity as PlayerGames;
pub use super::players::Entity as Players;
pub use super::tags::Entity as Tags;
